### ISSUE TITLE
Weird error report

### ISSUE THREAD

**Issue by Workaja** [SupianIDz/OctopyFramework#1]
**Describe the bug**
It show weird information when it show an error on error page.

**To Reproduce**
1. Change the view into somewhat not existed
2. Call the url from web browser

**Expected behavior**
It show error lines that not weird like that

**Screenshots**
![image](https://user-images.githubusercontent.com/40653902/56373795-f381da00-622b-11e9-94e0-ec7de3e2fd56.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome
 - Version 73.0 (latest)

**Comment by SupianIDz** [comment]
Issue have been fixed in next commit :+1: .
