### ISSUE TITLE
RuntimeException  : No application encryption key has been specified. in installation process

### ISSUE THREAD

**Issue by kasfil** [SupianIDz/OctopyFramework#6]
**Installation process throw an error**
 
**RuntimeException  : No application encryption key has been specified.**

I use docker for development process, when i wanna try this beautiful framework the installation process throw an error.
Any one suggestion?

![Screenshot from 2019-08-16 14-38-38](https://user-images.githubusercontent.com/46927505/63151427-b12ea500-c033-11e9-95d9-3c1e8388f154.png)

**Comment by SupianIDz** [comment]
hi, this issue was fixed a few months ago.  please install this framework directly from the source.

```
git clone https://github.com/SupianIDz/OctopyFramework

cd OctopyFramework

copy .env.example .env

php octopy key:generate
```

This issue only occurs when installing using a composer due to different versions, sorry for the inconvenience
